### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [Shivamdhuria/FoodRecipe#1]
Hello, @Shivamdhuria  I am a Graphic Artist and would like to design a logo for your project for free. If you are interested and will give me permission I will begin asap. - [Tobaloidee](https://steemit.com/@tobaloidee)

**Comment by Shivamdhuria** [comment]
Hi @Tobaloidee ,
You're free to design one but I won't be releasing this app on playstore, it's more of a personal project.
However if you still want to contribute, go ahead!

**Comment by Tobaloidee** [comment]
Thanks for the feedback! I will design and show you here after 😊

**Comment by Tobaloidee** [comment]
Hi @Shivamdhuria  here's what I came up with. I hope you like it! 

I made a unique and meaningful logo that features the needed representation for food and recipe.
![FOODRECIPE-01](https://user-images.githubusercontent.com/36028424/56142454-47dd4d80-5fd1-11e9-8710-0c93253fd34b.png)

**Comment by Shivamdhuria** [comment]
@Tobaloidee ,This is amazing!

**Comment by Tobaloidee** [comment]
I will make a PR after I finalize the files later @Shivamdhuria  I will do that when I get home. I am glad that you like it! 👍😊

**Comment by Tobaloidee** [comment]
@Shivamdhuria  Here's the PR #2 with the logo upload & readme update..And also, you can download all the other versions and formats of the logo [HERE](https://drive.google.com/drive/u/0/folders/1ch3SH275eKT72-3U66JXZcUR7_L6Ojrx)

Thanks again and best regards!
-Tobaloidee

**Comment by Shivamdhuria** [comment]
@Tobaloidee  I'll definitely contact you when I am making anything serious.
Thank you!

**Comment by Tobaloidee** [comment]
Surely I will wait for that @Shivamdhuria  You are welcome!
